---
# Create config dir
- name: Create config dir
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ gfreezy_traefik_conf_dir }}"
    - "{{ gfreezy_traefik_services_conf_dir }}"

# Copy traefik config dir to remote host
- name: Copy traefik config dir to remote host
  ansible.builtin.template:
    src: ./templates/traefik.yml.j2
    dest: "{{ gfreezy_traefik_conf_dir }}/traefik.yml"

- name: "Create network {{gfreezy_traefik_network}}"
  community.docker.docker_network:
    name: "{{ gfreezy_traefik_network }}"
    state: present

- name: Deploy Traefik reverse proxy
  community.docker.docker_container:
    name: traefik
    restart_policy: always
    image: "traefik:v2.10"
    comparisons:
      "*": strict
    network_mode: "{{ gfreezy_traefik_network }}"
    command:
      - "--configFile={{gfreezy_traefik_docker_traefik_conf}}/traefik.yml"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    env:
      CLOUDFLARE_DNS_API_TOKEN: "{{ gfreezy_traefik_cloudflare_dns_api_token }}"
    volumes:
      - "{{gfreezy_traefik_conf_dir }}/traefik.yml:{{gfreezy_traefik_docker_traefik_conf}}/traefik.yml"
      - "{{gfreezy_traefik_conf_dir }}/letsencrypt:{{gfreezy_traefik_docker_traefik_conf}}/letsencrypt"
      - "{{ gfreezy_traefik_services_conf_dir }}:{{gfreezy_traefik_docker_traefik_conf}}/conf"
      - "{{ gfreezy_traefik_custom_certs_dir }}:{{gfreezy_traefik_docker_traefik_conf}}/certs"

- name: Find which of blue/green is running
  ansible.builtin.shell: |
    docker ps -f label=service-name={{gfreezy_service_name}} --format {%raw%} {{.Names}} {%endraw%}
  register: old_gfreezy_service_names

- name: Debug old_gfreezy_service_names
  ansible.builtin.debug:
    var: old_gfreezy_service_names

- name: "Deploy both blue and green services"
  community.docker.docker_container:
    name: "{{gfreezy_service_name}}-{{service_color}}"
    restart_policy: always
    pull: yes
    image: "{{gfreezy_service_image}}"
    comparisons:
      networks: strict
      image: ignore
    capabilities:
      - SYS_ADMIN
    network_mode: "{{ gfreezy_traefik_network }}"
    labels:
      "service-name": "{{gfreezy_service_name}}"
      "service-color": "{{service_color}}"
    volumes: "{{ gfreezy_service_docker_volumes }}"
    env: "{{ {'TZ': 'Asia/Shanghai'} | combine(gfreezy_service_docker_env) }}"

  loop:
    - "green"
    - "blue"
  loop_control:
    loop_var: service_color

- name: Find all services alive
  ansible.builtin.shell: |
    docker ps -f label=service-name={{gfreezy_service_name}} --format  "{% raw %}{{.Names}}{% endraw %}"
  register: all_gfreezy_service_names

- name: Debug all_gfreezy_service_names
  ansible.builtin.debug:
    var: all_gfreezy_service_names

- name: Set template variables
  set_fact:
    template_gfreezy_service_names: "{{ all_gfreezy_service_names.stdout_lines }}"

- name: Debug template_gfreezy_service_names
  ansible.builtin.debug:
    var: template_gfreezy_service_names

- name: Bring all services to traefik
  ansible.builtin.template:
    src: "./templates/service.yml.j2"
    dest: "{{ gfreezy_traefik_services_conf_dir }}/{{gfreezy_service_name}}.yml"

- name: Set old_gfreezy_service_names if empty and multiple services exist
  ansible.builtin.set_fact:
    old_gfreezy_service_names:
      stdout_lines: "{{ [all_gfreezy_service_names.stdout_lines[0]] }}"
  when:
    - old_gfreezy_service_names.stdout_lines | length == 0
    - all_gfreezy_service_names.stdout_lines | length > 1

- name: Debug old_gfreezy_service_names
  ansible.builtin.debug:
    var: old_gfreezy_service_names

- name: Find service names not in old_gfreezy_service_names, retain only 1
  set_fact:
    template_gfreezy_service_names: "{{ (all_gfreezy_service_names.stdout_lines | difference(old_gfreezy_service_names.stdout_lines[:all_gfreezy_service_names.stdout_lines|length - 1]))[:1] }}"

- name: Debug template_gfreezy_service_names
  ansible.builtin.debug:
    var: template_gfreezy_service_names

- name: Ensure at least 1 service is running
  ansible.builtin.assert:
    that:
      - template_gfreezy_service_names | length > 0
    fail_msg: "No service is running"
    success_msg: "At least 1 service is running"

- name: Remove old services, Keep only new services from traefik
  ansible.builtin.template:
    src: "./templates/service.yml.j2"
    dest: "{{ gfreezy_traefik_services_conf_dir }}/{{gfreezy_service_name}}.yml"

- name: Wait for API to return matching data
  vars:
    traefik_api: "127.0.0.1:8080" # replace with traefik api address
  block:
    - name: Make an HTTP request to the API
      ansible.builtin.uri:
        url: "http://{{traefik_api}}/api/http/services/{{gfreezy_service_name}}-service@file"
        return_content: yes
      register: api_response

    - name: Extract the container IPs
      set_fact:
        container_ips: "{{ template_gfreezy_service_names }}"

    - name: Debug container_ips
      ansible.builtin.debug:
        var: container_ips

    - name: Real IPs
      set_fact:
        real_ips: "{{ api_response.json.loadBalancer.servers | map(attribute='url') | map('regex_replace', '^http://(.*?)\\:.*?$', '\\1') }}"

    - name: Debug real_ips
      ansible.builtin.debug:
        var: real_ips

    - name: Compare API server URLs with container IPs
      set_fact:
        is_match: "{{ container_ips == real_ips }}"

    - name: Wait and retry if not matched
      ansible.builtin.pause:
        seconds: 10
      when: not is_match
      until: is_match
      retries: 10

- name: "Stop {{gfreezy_service_name}} old service"
  community.docker.docker_container:
    name: "{{ old_gfreezy_service_names.stdout_lines[0] }}"
    state: absent
  when: old_gfreezy_service_names.stdout_lines | length > 0

